# Generated by Django 3.1.6 on 2022-06-22 15:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0017_auto_20220614_1115'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livre',
            name='date_update',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 22, 17, 39, 58, 719583)),
        ),
        migrations.AlterField(
            model_name='publication',
            name='date_published',
            field=models.DateField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='publication',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
