# Generated by Django 3.1.6 on 2022-06-29 16:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0018_auto_20220622_1740'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livre',
            name='date_update',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 29, 18, 20, 9, 232536)),
        ),
    ]
